# Generated by Django 6.0 on 2025-12-30 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='message',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user_message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
